//
//  File.swift
//  
//
//  Created by James Truher on 7/22/20.
//

import Foundation

#if !os(macOS)
import UIKit
#endif


public enum BackgroundImage : String, CaseIterable {
    
    case diagonalbrick, cardbordertemplate, toparrow, crisscross, cardinnerradial4, box, eight, diagonal, heartshape, cardinnerradial1, toparrowdark, darkdots, themehighlight, cardinnerbrick, darkgrid, cardbackalt3, nine, cardbackalt1, cardinnerradial2, clown, cardinnerradial3, scrolldots, cardaltgradient5, cardaltgradient4, seven, one, cardinnercrisscross, jack, twobytwo, cardaltgradient3, lightvertical, cardaltgradient2, five, diamondshape, cardaltgradient1, bottomarrow, cardbackcenter3, spaceysquares, cardbackborder5, cardbackborder4, shinning, queen, cardbackcenter2, six, cardbackcenter1, two, ace, twobytwoalpha, cardbackcenter5, heartshapefat, spadeshape, cardbackborder3, cardbackborder2, zero, cardbackcenter4, three, four, cardbackcenter6, orbs, squigglebrick, cardbackborder1, cardinnerscales, depthbox, windowtop, king, diamond, vertical, theme, clubshape, box_checked, bottomarrowdark, ten, cardinnerbordertest
    
    var name : String {
        return "backgrounds_(self.rawValue).png"
    }
}

public extension BackgroundImage {
    
    var image : UIImage {
        return UIImage.convertBase64StringToImage(imageBase64String: base64)
    }
    
    var base64 : String {
        switch self {
            
        case .diagonalbrick:
            return "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAAXNSR0IArs4c6QAAAAlQTFRFAAAA////AAAAc8aDcQAAAAN0Uk5TAP//RFDWIQAAADVJREFUGJVjYIQCJiYIzYBDgAkMcAvAlINoTAGYUpgQNgFGFIApgMoFasErAHcHDgEUvyAEAKiIATXDtFlKAAAAAElFTkSuQmCC"
        case .cardbordertemplate:
            return "iVBORw0KGgoAAAANSUhEUgAAAGQAAACMCAMAAAC9K/yJAAAAAXNSR0IArs4c6QAAAAlQTFRFAAAA////AAAAc8aDcQAAAAN0Uk5TAP//RFDWIQAAAHlJREFUaIHt2jEKwCAQRcHF+x86IAbSCAn4lxTzCktHtrDaqp5GuA5jKssKzmmeSWPdD4FAviFHv5Itcuz5EAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCOR3SMdSciIIBPIaiSrjRsJVg5Kc06MLxFQKKd3T+sIAAAAASUVORK5CYII="
        case .toparrow:
            return "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAAXNSR0IArs4c6QAAAAlQTFRFAAAA////AAAAc8aDcQAAAAN0Uk5TAP//RFDWIQAAAD5JREFUGJWNz0sKACAIRVG7+190+ElLCnojPaSS0CKMIwk0YEkA+caBmjLI+YC6g4HGWy3uO36A3PT+ywYtE7isAV2vjFz2AAAAAElFTkSuQmCC"
        case .crisscross:
            return "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAAXNSR0IArs4c6QAAAAlQTFRFAAAA////AAAAc8aDcQAAAAN0Uk5TAP//RFDWIQAAADRJREFUGJVjYIIDRjBgwBBgZIRxIULYBGBMCI1NAMEFAUwBVC42AYRx+AQIuwPhNag7kAUAy0ABeX/SoMEAAAAASUVORK5CYII="
        case .cardinnerradial4:
            return "iVBORw0KGgoAAAANSUhEUgAAAGQAAACMCAMAAAC9K/yJAAAAAXNSR0IArs4c6QAAAAlQTFRFAAAA////AAAAc8aDcQAAAAN0Uk5TAP//RFDWIQAAAp5JREFUaIHtm+uOAiEMRoX3f+hN1hi59PJ9bXVYVyZmfphQDqeFUfF2e0/rRGvLHWlsjFizgzTi1bvKdwDJvaEcqSDppgd5jrMN9/Ua31e5jnAiO9jHbnq5kGQeM3qpXJeRyPOPM2x+CJJ17cDXyD1IzIfp5QAnJbkFk4TXRiFIzsfOxJHsPL3j+bUGeUFuQSTsHmyR1PgQvcBOMvklOynNLZfEXic5J7U+5jF4JPbeq8yNSjL2WZ5bJgk3hxbT6OQV12/foJPRA8MwT9futtCLQpLZt2wnQJ9tuWMsqpO63JKcABfEMcyfQFKxb+lOnLFbLzum44RnkLzMTkAf7vhRJ9FL4nk4gcffAl5EJxXPRCvJi3Ort1OczD7WlnQS4dHrxO1zzy2QoYlOavYt0ontY/ZCOMmzBOokn1uTE5ABND7y3EkSPhAvipPMFXbiM6gcWp1APgwn6/oF1QnmQ2dhncC5BTvB8wt24tSJtgObXg6uk0BuHVcnezS1Z6JOcB8Oz1wnUH4BM0Q5qcktvk5g41SdcE5cEqJOmu+juE4cjn9eJ8T6dXSdfPcTu9/vc9cYM/L5hHiep5xYPN/PJz5P0In7PKzvvoSTGg6J5ZrP8T3FUvZ91+7DWrcEJzkOjeWvfd8l+3iSAH1KHpAaGYNc7STMgTqJeZGcwP015e7N3Um/nzzGzfvomhPei14jT5KqNV6Je+LvjDEW4vf4vJMO9RXwYTjhvVgs1zvZvdgvrX3auZW9v9L8gs4SZXysQeJ7lePlA8534SQ713hHmn7mLrbOR+pEjo3nlRSkMrd4klzDzgsnfGhBlLbmFZ5fn31eeObR1vsujl2cwyPO1SN+XJbL/+vArPHmGnPM/0+43DrRydhSa/3tDSi397QfwzJXnF4DOc0AAAAASUVORK5CYII="
        case .box:
            return "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAAXNSR0IArs4c6QAAAAlQTFRFAAAA////AAAAc8aDcQAAAAN0Uk5TAP//RFDWIQAAABRJREFUGJVjYEIDDEyMKGC4C6ABAKjwAT10CJUpAAAAAElFTkSuQmCC"
        case .eight:
            return "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAAXNSR0IArs4c6QAAAAlQTFRFAAAA////AAAAc8aDcQAAAAN0Uk5TAP//RFDWIQAAACpJREFUGJVjYAACJihggAImJjQRKAtZAJUmSgDNDAxrsbmD+tZieA7FWgBrUADJgqFU3QAAAABJRU5ErkJggg=="
        case .diagonal:
            return "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAAXNSR0IArs4c6QAAAAlQTFRFAAAA////AAAAc8aDcQAAAAN0Uk5TAP//RFDWIQAAACNJREFUGJVjYAIDRkYYzYBVAMFlYsImgMzFJoDKxSYwSNwBAO8QAcHN6P/UAAAAAElFTkSuQmCC"
        case .heartshape:
            return "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAAXNSR0IArs4c6QAAAAlQTFRFAAAA////AAAAc8aDcQAAAAN0Uk5TAP//RFDWIQAAACxJREFUGJVjYCAGMDExIVFgBogJpaAMOKCSAAM6H1kEyWUofJgImutR+PgAAI9OAP0uAUfkAAAAAElFTkSuQmCC"
        case .cardinnerradial1:
            return "iVBORw0KGgoAAAANSUhEUgAAAGQAAACMCAMAAAC9K/yJAAAAAXNSR0IArs4c6QAAAAlQTFRFAAAA////AAAAc8aDcQAAAAN0Uk5TAP//RFDWIQAAAlNJREFUaIHlmAGvwiAMhIX//6ONz8wxWMtdKVh8JcsSXTjOr7cxH481lYrKf0dn5M+h1ee6WqOujOnm6lyNtwg4F+qhLtVJZvSVUYqQfpB6X6s4IXhIR+OkO5+NR5cJ3NOd/qpFCD84l3lMGicxckJ7EZlM8uLLJEt+CCYxciJyoe9djkxMPM5Z7UzsXPxycvXQYQLTdXEC+JDV9syJlHmFyXY5yTQTnbSZCZ0TmAn066zPyZ3i7jkJ+DyhPeTqvPPz5B/tuyAfsfZdzdjk/QTor0g5od4bVSabvceLTiY+U8Cc+P23ktD5MD/ndT7/d5XqqpNv5WQGEzh7/fvX9RqfexfsZNL9K3FM7J7uc0L5kXdEc3ICOXHmclzTZXJq+zihGUs77fquv5iJsa+QzENMRrnIOXHgcow9coL0F5ETu6c7EXqu3q4IcDLOxZAThgvsZJyLzMTjucs5GdM15qTkIvGhnYxx0Zk4caFyYtVtRYa4lGcjE+63PK+TRFy50Dmx6GpM3DI/kJNyHfV6ys8RJmud2LikDhO3QedE9iUfkXIir7/upfp8zyQ1c3yHCcNDY9LOtdYJzkVnkpo51jOp11L7Kz9/VU/EhYvRCdNbPSdOXIaZHGu5Ox+FiAxzGXCC8UBzMszFhUmvUBG7p+TmRO8vNCdDXMIwkfd0AI9AThy4BHFyLZmP8vwN5ERfe7fHAjl5192eATqCOeG4XHosmJNrUXuigE7ovkrxmbwKyc2wCFy8yC8y+SURrb+K7zdw8lsi0l672HNv4gQTma7yWFNP6PRHgDRlv0wAAAAASUVORK5CYII="
        case .toparrowdark:
            return "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAAXNSR0IArs4c6QAAAAlQTFRFAAAA////AAAAc8aDcQAAAAN0Uk5TAP//RFDWIQAAADVJREFUGJVjYEIDDEyMKAAuwIQmAFSLIgDWjSQANQ8uALcBKoBkJ1gABeAwgxwBbH5BEkADANDVAYp9RyHqAAAAAElFTkSuQmCC"
        case .darkdots:
            return "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAAXNSR0IArs4c6QAAAAlQTFRFAAAA////AAAAc8aDcQAAAAN0Uk5TAP//RFDWIQAAACFJREFUGJVjYAICRkYmJhjNgFUAGWAKICvHLkDYjEHiDgD90AHhqTy9sAAAAABJRU5ErkJggg=="
        case .themehighlight:
            return "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAAXNSR0IArs4c6QAAAAlQTFRFAAAA////AAAAc8aDcQAAAAN0Uk5TAP//RFDWIQAAADdJREFUGJVjYAABJjBggAEmOEDnQ0RANCMYQEVAfIg0I1gAxgepAIvQRADDWkyHYTgd03Oo3gcAxbsBcy/OlbIAAAAASUVORK5CYII="
        case .cardinnerbrick:
            return "iVBORw0KGgoAAAANSUhEUgAAAGQAAACMCAMAAAC9K/yJAAAAAXNSR0IArs4c6QAAAAlQTFRFAAAA////AAAAc8aDcQAAAAN0Uk5TAP//RFDWIQAAAaNJREFUaIHtmoFugzAMRDH//9FTR4uCa4cl3Nkt86Eo0jb1/HYc0cSWpVQqlUrfLFlF7DXxWRM6mUye01zboRMPo6wCvFJJEFnsewqJc69fW5zRPRJkBnoPJ2FefJIdh5nJtkeQyNI7D1ArlETkHpmQr8pkSNWTob16MkGy6Q6ZVE/+uFdPJkg2hWRCY9J//6B64YsyuWOCyCCbBNeLbJJNd8ikeqL2CJAuCfL84JP0UHDnyCeQYNYnkIjcIxPUlU+yCbBHkHRMcD0Jet1g4fx+EZjJmwl0+lYHE1w//LbQSFoWeBbWMww4uZYi4azKZEgBPYkhadtIysR8PkKlHZDnyL74GJYJI5MsEu5Z8t2ZaBcswksWCfMs4ZFok4hnF3L8VkZPCH3RJBSkg4n+zcGy0Y3kxOO4MLtCQumYAPuSFwq6K4kkD7Ezibm9wOdKIokIMhPbA0riWGD/C9I1MQbBkzy+uR5/ZDoT16R563iNxHdYmncoR5LhdWZyPokBPkMyYmJmkk8yqLGTZFJv8zNI9gxfd9RgptOmeBLD5LwnpX+iHyD5KmRzoCt0AAAAAElFTkSuQmCC"
        case .darkgrid:
            return "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAAXNSR0IArs4c6QAAAAlQTFRFAAAA////AAAAc8aDcQAAAAN0Uk5TAP//RFDWIQAAABlJREFUGJVjYGRkYkLGDBgCTGgAU2AYmQEA6pABwVuAJeIAAAAASUVORK5CYII="
        case .cardbackalt3:
            return "iVBORw0KGgoAAAANSUhEUgAAAGQAAACMCAMAAAC9K/yJAAAAAXNSR0IArs4c6QAAAAlQTFRFAAAA////AAAAc8aDcQAAAAN0Uk5TAP//RFDWIQAAANNJREFUaIHt20EKwzAQBEGv/v/oQHJwCDaiYXYNoUcPaMoI3XwcM1vN+zSqde/Kql5IzUaq7ZyRarxUp6QrogRNCdqDksxTspGEI+tGkvhGW0k0ogRFlKCIEhRRgiJKUEQJiihBESUoogRFlKCIEhRRgiJKUEQJiihBESUoogRFlKCIEhRRgiJKUEQJiihBESUoogRFlKCIEhRRgiJKUEQJiihBESUoogRFlKDI/0sS20qikXUpCe9aEp4SNCVo85K28y1p3GBk4heq0MN7v65L9bMXSCoUf1zxuXYAAAAASUVORK5CYII="
        case .nine:
            return "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAAXNSR0IArs4c6QAAAAlQTFRFAAAA////AAAAc8aDcQAAAAN0Uk5TAP//RFDWIQAAACxJREFUGJVjYAACJihggAImJjQRKAtZAJUmTwDDUJwOYUAFJAhAGcTYAmIDAGb0AL21EniuAAAAAElFTkSuQmCC"
        case .cardbackalt1:
            return "iVBORw0KGgoAAAANSUhEUgAAAGQAAACMCAMAAAC9K/yJAAAAAXNSR0IArs4c6QAAAAlQTFRFAAAA////AAAAc8aDcQAAAAN0Uk5TAP//RFDWIQAAAHhJREFUaIHt1EEKwCAMRUHx/oculFKKO2m+iMzbuMuAgbS2ph5uhXErhyHRfT9vyninQyCQWaTskGyAVHwRBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAjkD1LRDkh1EAhkCokp/YtEOwqJK6l9D13HqxPBJbwHOAAAAABJRU5ErkJggg=="
        case .cardinnerradial2:
            return "iVBORw0KGgoAAAANSUhEUgAAAGQAAACMCAMAAAC9K/yJAAAAAXNSR0IArs4c6QAAAAlQTFRFAAAA////AAAAc8aDcQAAAAN0Uk5TAP//RFDWIQAAAiVJREFUaIHtmsGOwyAMROv8/0fvIWpFgg0ee5yQVUARe1gJpo9naNTP55q2BZoAT3QOrPkmma9XmrHrCyXZG8LhkO3mJNKMwOe/PBM7l5WxGRdIMl7z85gEHC9PIt049iTBYTkmcy+uT9LzsJMQ6tVSTAiup5P4aqbuCdGPciZtTmsSGg9CEt+d4jhJAQ8ak9k+0yah8ggmwe6sRyZFPChMPN77PLk2Cc5DNtuT9n/uYeKvvz0Tuh+BJPH7xD5JkR8pJggPzZOSTM4kcR4WEzoXiMnc9VGSQh7OJOP6FGVC6vIbYU8ie+w7SVnd2nxMbC5RJjQO7ehKop8fWJJSHpMkeT80JgQO+uP2JPOZ6p4QujR/T5Jw9gPJE5uHm0k2S+9JkoP2wJ5kmVA5QEwYNUevXUQeAybcevllEuz2+qUZh0xYZwDFk9n+UpLwz689CZGD1kBPMkkKeazuiZ8H6EkuCZmHK8minsyayYR5dw17gjg/9YTRQU9wHkMmt3uC1eCJJ6GurADwJMZjyITpPMkTKEnScePUus+TJI/ujQHBk1ASLg95qieirAj3JJKF48nkdgee8TgPk0mCh/rc4QmlbqmTlPIwmbC5wDfIlTxp29M9kTOTwrp1SlLC4zdJKQ+TCZvLYz3hMFnLk0OS1xM8SQGX9zxZy5PMvYvOJLgj5Dz+N08e8f1kmOOBnph53u/xEJeq913Sjle97yL+llfUFXyuaX9bxFMExAIL1gAAAABJRU5ErkJggg=="
        case .clown:
            return "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAAXNSR0IArs4c6QAAAAlQTFRFAAAA////AAAAc8aDcQAAAAN0Uk5TAP//RFDWIQAAADtJREFUGJV1z1EKACAIA1C3+x9ahonBdB8mLzIMEiBVFTIM6mgAdujo4oJ6tMO0b+gBE4f/yx1mrRpukLwQAWE3CY1wAAAAAElFTkSuQmCC"
        case .cardinnerradial3:
            return "iVBORw0KGgoAAAANSUhEUgAAAGQAAACMCAMAAAC9K/yJAAAAAXNSR0IArs4c6QAAAAlQTFRFAAAA////AAAAc8aDcQAAAAN0Uk5TAP//RFDWIQAAApBJREFUaIHtmtluhTAMRAn//9GVWrXK4mXGNiFVa3TFy1WG4diJgVzXnrgfjh0anyrEv9t0fkQkGH9JpAG/tEhBoCJ9XrWbzLMDnKz3v0W4HODkK9L59bKTkYN3mJ6OYCLn1nx2uLzohOMxcoFFikMTKcwtyklgjldFYjxMLjQTsocwRaK5JV4D6CSx9ooicR4qF8hJzocsks2tRdtxss6PZB0KInkeIheXSUFvt4jk6l25fzATKmdNJzVMFi+mk5rc0piU5pbpJLJueU7cMZvwwzRBJhRnw0k/rnGY188xqe2JZiYED5wLwAT3oHHpRSAekI9J02TCHpqfnol7/X3Afiwmhf02zoTOr2eZaE7M2lt5gFxsJvE1OMEE8UIycTw4M6ReJ05eWYHkWHmdSFy+RRweNhPvvnFMgBk+wMT24fhB6sTIBMpHmonLhWQyqqkjh5kgYXFhmTj5lWISzq0WYQIRn/2UMKmskzm3hJF3M2l3uE7c0f/rJJNbZJ3cgxrl59A6OYpJu8N18t56Ut13BfrHojXe09vedwljv9d3hZkAXHQP4ecTkwvpBXo+CfaPP5pbn0/cccfZ0eHhM4n50HiMIqAPMLcGTYcJ40fzUfBuBcmB7e+7grm1jYnOQxJxx23TGdHc/F74RsYEVq1ez2MC3Tt5TNNJ7B7FmfCaVn4R3096Lpwm+Z1R5hCrkwwXQfO174zZ/Fo009/jfR9nfI8ffTTlzDHJ+VD9wPtWWA62k6gfQ/ulfSsxH83SDu3vYnhYIpF5XtX+dfu7VO1D90GSPBCRkkD2pmJrluHnQCbr/A7l8lFMpH4I4mGLFAazrz481x/kJNkTHeRkDHbNOs1Joic6zElO5HGVa098AMJVW61VM6tHAAAAAElFTkSuQmCC"
        case .scrolldots:
            return "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAAXNSR0IArs4c6QAAAAlQTFRFAAAA////AAAAc8aDcQAAAAN0Uk5TAP//RFDWIQAAABpJREFUGJVjYGJiBAMYzYAhgMwB0ZgCw8gMAKtQAUGHVukqAAAAAElFTkSuQmCC"
        case .cardaltgradient5:
            return "iVBORw0KGgoAAAANSUhEUgAAAGQAAACMCAMAAAC9K/yJAAAAAXNSR0IArs4c6QAAAAlQTFRFAAAA////AAAAc8aDcQAAAAN0Uk5TAP//RFDWIQAAApBJREFUaIHtmtluhTAMRAn//9GVWrXK4mXGNiFVa3TFy1WG4diJgVzXnrgfjh0anyrEv9t0fkQkGH9JpAG/tEhBoCJ9XrWbzLMDnKz3v0W4HODkK9L59bKTkYN3mJ6OYCLn1nx2uLzohOMxcoFFikMTKcwtyklgjldFYjxMLjQTsocwRaK5JV4D6CSx9ooicR4qF8hJzocsks2tRdtxss6PZB0KInkeIheXSUFvt4jk6l25fzATKmdNJzVMFi+mk5rc0piU5pbpJLJueU7cMZvwwzRBJhRnw0k/rnGY188xqe2JZiYED5wLwAT3oHHpRSAekI9J02TCHpqfnol7/X3Afiwmhf02zoTOr2eZaE7M2lt5gFxsJvE1OMEE8UIycTw4M6ReJ05eWYHkWHmdSFy+RRweNhPvvnFMgBk+wMT24fhB6sTIBMpHmonLhWQyqqkjh5kgYXFhmTj5lWISzq0WYQIRn/2UMKmskzm3hJF3M2l3uE7c0f/rJJNbZJ3cgxrl59A6OYpJu8N18t56Ut13BfrHojXe09vedwljv9d3hZkAXHQP4ecTkwvpBXo+CfaPP5pbn0/cccfZ0eHhM4n50HiMIqAPMLcGTYcJ40fzUfBuBcmB7e+7grm1jYnOQxJxx23TGdHc/F74RsYEVq1ez2MC3Tt5TNNJ7B7FmfCaVn4R3096Lpwm+Z1R5hCrkwwXQfO174zZ/Fo009/jfR9nfI8ffTTlzDHJ+VD9wPtWWA62k6gfQ/ulfSsxH83SDu3vYnhYIpF5XtX+dfu7VO1D90GSPBCRkkD2pmJrluHnQCbr/A7l8lFMpH4I4mGLFAazrz481x/kJNkTHeRkDHbNOs1Joic6zElO5HGVa098AMJVW61VM6tHAAAAAElFTkSuQmCC"
        case .cardaltgradient4:
            return "iVBORw0KGgoAAAANSUhEUgAAAGQAAACMCAMAAAC9K/yJAAAAAXNSR0IArs4c6QAAAAlQTFRFAAAA////AAAAc8aDcQAAAAN0Uk5TAP//RFDWIQAAAlRJREFUaIHtm+tugzAMRmve/6GnSqVNje18vuSC1lgI7U+Tw/FH2cgejzmDjrH1nONoBhUen/GcZDQJMZIPT5ZrJYm+LqSO5syPNU4qfHAvM0lyPnpe5jvRWTQmq6c+XmaR5Dxotc6J34e19u9jjZPKCjoh5dwlqci6xrDKyYgCnZDjUEmqfbQMQSe+vnqTjPNxVofE40P3IjipLIeTeF+9SWrXLpVAoq+XlHOPizkZUYCTfN7X5sT2QeznHlfjZDqJxmOvXbuv7ZMTZMiMX05GlpGTTOZ5rXAS89F6kbhWdVe0t3QvfpLAk0RDkvNheZmQE8GJno+4F58T7xOETJLzITPFcuLoK4FkRG9hJCSuwOVFzEnFYDkJ+XB56eQkx3AWRmL5ALy8SGruWxqPx0m4v4pzInGgObGfJro8z0nKffDZUSeJvA/OSdSJ/Wk2Sa0PvgrECdJbuJMdcmJ/2j1zcr0iuJODan1gTrAriTjp280yxXICMwhOfjnpzX7/75OzvM9dxM6x75MRXn7PXS6ebX8/add935yE+mtITvjsmd/jIR8XJ/KViDPgOUG84CRDc/Jv/951EOTBIKnJS0VO8k6uPER9JrurZ5OM8fEi2f79CXaX2eP9CeJHZvsi2fI9o/+uv9d7Rs2L3WsXJ7/38f2C38dneFhOFu9b6fFZte6bsb9ui+fKtef+rkgN3Qd5Fkji98BIMvtRtfrH+yDP4tcf8/EiqdwvTOLnrNvDXdFbLdMd9tVra99pX33Ui8S07v9Pqo5zzCJ5NPNW9xa9QGaMP8F7Skz3ghX/AAAAAElFTkSuQmCC"
        case .seven:
            return "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAAXNSR0IArs4c6QAAAAlQTFRFAAAA////AAAAc8aDcQAAAAN0Uk5TAP//RFDWIQAAACJJREFUGJVjYGBgYEIABjDAEIABLAL4FVDKJ0YBQSeSIgAAUZAAffVEHksAAAAASUVORK5CYII="
        case .one:
            return "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAAXNSR0IArs4c6QAAAAlQTFRFAAAA////AAAAc8aDcQAAAAN0Uk5TAP//RFDWIQAAACFJREFUGJVjYIACJiYGFMCEJsBEUADTjMEqwMSE5niEAAAsrgBbeoe+QwAAAABJRU5ErkJggg=="
        case .cardinnercrisscross:
            return "iVBORw0KGgoAAAANSUhEUgAAAGQAAACMCAMAAAC9K/yJAAAAAXNSR0IArs4c6QAAAAlQTFRFAAAA////AAAAc8aDcQAAAAN0Uk5TAP//RFDWIQAAAI9JREFUaIHt08EJwDAIAMDo/kMXK6QTaD8nBEk+YvTO2YmMiMyMofzWiL6NnS4y2EXl/q2KfhvJXyfV11BenMlgF3e7JueRd4U54YQTTjjhhBNOOOGEE0444YQTTjjhhBNOOOGEE0444YQTTjjhhBNOOOGEE0444YQTTjjhhBNOOOGEE0444eRvJ2djJgvxAEP5S++2TspOAAAAAElFTkSuQmCC"
        case .jack:
            return "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAAXNSR0IArs4c6QAAAAlQTFRFAAAA////AAAAc8aDcQAAAAN0Uk5TAP//RFDWIQAAACFJREFUGJVjYIAAJihgYMAlABZjQAWDUADCxOsRTI8hAAA9tgBt88D5QQAAAABJRU5ErkJggg=="
        case .twobytwo:
            return "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAAXNSR0IArs4c6QAAAAlQTFRFAAAA////AAAAc8aDcQAAAAN0Uk5TAP//RFDWIQAAABpJREFUGJVjYGJiZETGDBgCqFwmJkyBYWQGAM0QAYGvefCZAAAAAElFTkSuQmCC"
        case .cardaltgradient3:
            return "iVBORw0KGgoAAAANSUhEUgAAAGQAAACMCAMAAAC9K/yJAAAAAXNSR0IArs4c6QAAAAlQTFRFAAAA////AAAAc8aDcQAAAAN0Uk5TAP//RFDWIQAAAjFJREFUaIHtmluOhCAQRcX9L7rHidiIVdQb0JaK4WMyyuF4aaMsS5+W1tjarrH+tUQeieivx3r020WiSdJO8r2u11G2XiTt+edWy09fJ7y5psYMexnjROMjVf83zgk9/1qGUU48S+kkIT2LxOoDGvv56OskooROMB88L4ATT4beTiKLcJIUB0oS4SP3Qif6vHdwshVCovUB8xVOIorhxH5fHSQxDGUBJPh4E9JTXLuTiGLkxC/vY5y0fdSN62Vc4ttzj48d89KbhOcBay2uwJzkAnJizTrkpacTmw/YyxgSyoeMofbCJzE8SWwXcfHR8jJm7dL5ODPUxSMx+ChIYr2MzomNQebE8gTxJfFzATMlsRPV/XU48V6Dy1G0SRx8hDnR5MTIsTuJynoeBU5CP03ocuLZNDkxeXHMyZUhlzQnKSm8TJqT61lIL845gTjkOaHPOGtOzD4OJ7PkhJqRNyc+LJKccGfmLjl5wu8JNSN3zInCy5TPXfjZZs8Jx8u9cmK6v6bKCcbFKiAnFiZpTiReaJJ5clL7ERWSEw0bPov8913qvAPvuzyaJifmcnrf1Z5F2XthVd5/7L0wxUbP4vv9RO8EX78wNt5q835nFFTA9/jROWl7ad1blI8OJI09EhofrdV/RE5oL1BP8Yzdt1LyaTxUJDEcZTnu78K5xu/v4nCtifby7oMkxp77H9svjK9n57+TJE/aLxy1rz73DJJ6/mU+dpLn7Ktfgu+t/2t0aB99BUjff12rZgAAAABJRU5ErkJggg=="
        case .lightvertical:
            return "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAAXNSR0IArs4c6QAAAAlQTFRFAAAA////AAAAc8aDcQAAAAN0Uk5TAP//RFDWIQAAABJJREFUGJVjYGJiBAMYzTCyBQCr0AFBdl/DfgAAAABJRU5ErkJggg=="
        case .cardaltgradient2:
            return "iVBORw0KGgoAAAANSUhEUgAAAGQAAACMCAMAAAC9K/yJAAAAAXNSR0IArs4c6QAAAAlQTFRFAAAA////AAAAc8aDcQAAAAN0Uk5TAP//RFDWIQAAAq5JREFUaIHtm9tugzAQRGP+/6MrtUnwZS8z612Q0thCSH1gfTiemhDn8bimHUJr4tGms3zMTauR28Yi8tjRrvLcQPLXeBbHC0HSlDNDEvMAebnFSdbcalYRpTHZ00ji44e8UE6i86svkscz3UuDxPLA+emdZPahNuxEGzfi5VWkwsd7LLSTNp1ZJ2VeTCf78+okyc274EYg4dZg2Y/upKLbTvLm1uwkneGwcsLV9XheTiq7TMLPadvL6aSE4fBzEr+uRAL1JhxYd5wE7s3lTp61J5IMHysP6ETyAXtZc5LFEnYS4xicVDxHwE7W8TeS50InQA/PrwonEo9DovtgvAxOMucX7cSbW56XEiczj0Eyjl1rCE+Zk96L62T1wTAMJJXP2wlORibYSTaH40T3wXkZnJi9tbXynhPcB+Ll7STvMx2ZEzbzkBPIC5HCu51AHJQXwMkuxy8J7QOz3fEIJLyPsepamXFCeAFzwvFk5MRatQCetJxYVfmcjJZNBjcnESd7OZGrwTxpObGqTk4cltWL0YucaB1b4785+eYkwhNd4z9jPbnvucvi2XGyn5PzqjhD5nMX/RxpOuF97Ds51KsoDG5OxjsU99GR5D4/zjwpOfGq/8fP8X1lkiXl3crJZJJQWaF8uE5sL/iMLnnfNb7fIN4LR310JDc7GXnkFRh0UuXFJVnHq/sgcpLz/yvoROYC/+sfyd8zjiwwiTV+mOf7PSPCAuXEGj/HYzhhmWQftJPo/bvs+3jimm06Y7XT961c7+RZN23fisVC7FuJs4D7u9qxsvV/l12sTrK9dLU/Yn+X7WT1MvuRD99JJlN3Tej3FO3Q6yMs9+6DtL34HlaSnbUKuH8OCcLh89TvF/ZJTh6NC2l376uXa0d4Kn7rsMyxj/r9CYLSnLMHckX7Aat4UrOJy50vAAAAAElFTkSuQmCC"
        case .five:
            return "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAAXNSR0IArs4c6QAAAAlQTFRFAAAA////AAAAc8aDcQAAAAN0Uk5TAP//RFDWIQAAACZJREFUGJVjYGBgYIIDBgjAIsCACqgjgGoJNhHKbYMxcHuOAZkPAFSIAJ07sWoFAAAAAElFTkSuQmCC"
        case .diamondshape:
            return "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAAXNSR0IArs4c6QAAAAlQTFRFAAAA////AAAAc8aDcQAAAAN0Uk5TAP//RFDWIQAAADBJREFUGJWNzzEKAAAIw8CS/z/awckIYseDok06kBkDSAwgMcAUkCxYlceVx6fX2gJaUACpN8UrdQAAAABJRU5ErkJggg=="
        case .cardaltgradient1:
            return "iVBORw0KGgoAAAANSUhEUgAAAGQAAACMCAMAAAC9K/yJAAAAAXNSR0IArs4c6QAAAAlQTFRFAAAA////AAAAc8aDcQAAAAN0Uk5TAP//RFDWIQAAAbVJREFUaIHtloEOgyAMRIX//+hFl0bAIhRovRprDMlGsru9vcm22UyMMQzdgVmZ6/iM6rurrqPIniNGfp2/Q7RqsiYvx4kuOybc3HGS8vLHhONhy6Tn+x/l4ZNJjc+znrRGwskvk1CsuEyk3lg2We14zgeXSYvTk57o8cD2RMLD2pOejD2Z+RuhiXy4rtae3GWqZXwrk1pX5CYyTmeT8gTwfBNZV1Qmcm9Qm8i6IjOpZU6z93pSW1GYlF3RmfT78m+iyEOdCXVEZ8JlbjGRnKCRmFA3T0woM62jTAKzIjBJPVnst3oTnovMk0Ff1D3Zp/RE4fwI58mEL2ZMlJ+Lak1yPmOeCH0x9USNh1KTqy/jTFA9UTqnqDZZ6UlnTxgm094oNlnhieB3B8Nk2hflJiFpkttTru/xZPr/S9mT/0qe5K+eq+x354XJMB9TT+53TfaDZSL2xcyT9q7JfrBMfHqS7/48edqT624fnpSZ29lRPEmbtMeLJ2XWdmYUT2je58lY9u7/MShPaDx4kmZtZ/bpybnbnyc0nyff82R83vc8+c5deJ5QlnZWNE/O1FvHp8x6stnMD9tsXcE/5nvBAAAAAElFTkSuQmCC"
        case .bottomarrow:
            return "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAAXNSR0IArs4c6QAAAAlQTFRFAAAA////AAAAc8aDcQAAAAN0Uk5TAP//RFDWIQAAADpJREFUGJVjYEIDDEyMKACHAFQ1kgBEkmgBmG6wSWAVCHuYoFqYEHxchjIiiTLAZJnQnA43B4tf0AAAu1QBXblue90AAAAASUVORK5CYII="
        case .cardbackcenter3:
            return "iVBORw0KGgoAAAANSUhEUgAAAGQAAACMCAMAAAC9K/yJAAAAAXNSR0IArs4c6QAAAAlQTFRFAAAA////AAAAc8aDcQAAAAN0Uk5TAP//RFDWIQAAAJ9JREFUaIHt2kEKgDAQBEH1/4/2B8bGRQRr9hpo6p5tMzOzz+zYZ+4yMtQ4fiR5unuSyxfL7fckDyMkKUKSIiQpQpIiJClCkiIkKUKSIiQpQpIiJClCkiIkKUKSIiQpQpIiJClCkiIkKUKSIiQpQpIiJClCkiIkKUKSIiQpQpIiJClCkiIkKUKSIiQp8iHJwB/FpWTi1pKB+4nEzMxe3QnvDQmNyg+6dgAAAABJRU5ErkJggg=="
        case .spaceysquares:
            return "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAAXNSR0IArs4c6QAAAAlQTFRFAAAA////AAAAc8aDcQAAAAN0Uk5TAP//RFDWIQAAACNJREFUGJVjYGJiZETGDBgCjGgAUwCkDL8A8WbAaEwBurgDAKDQASEn+VAWAAAAAElFTkSuQmCC"
        case .cardbackborder5:
            return "iVBORw0KGgoAAAANSUhEUgAAAGQAAACMCAMAAAC9K/yJAAAAAXNSR0IArs4c6QAAAAlQTFRFAAAA////AAAAc8aDcQAAAAN0Uk5TAP//RFDWIQAAASNJREFUaIHtm8ESgyAMBYX//+i2Ah07LZCUEJXZXN5F3RnzVi+6bT4TJ09ihKmzU2JIwBz9FB9YwhXyPDOFIMMer7P7eYTkiwRRhpRRlN4Qh51MHio8VOFoNo0KR7OH7lmQ957MIF+L/6y0DaTliRnkV4VdINkDY0jFEzMInqggeDIMwZPLQfCkDsETFQRPVBA8GYbgyeUgeFKH4IkKgicqCJ4MQ/DkchA8qUNO9sR+8Wt64nK7VmnXSjKuU2FPT+a+fvGkDsGTW0DwRAHBkxYET1QQPFFB8OQWEDxRQPCkBcETFQRPVBA8uQUETxQQPGlBTvfEbBqeBEn++3n1YU/9FB9Ywg8yeVxvV2mXKEPKKEpvCBWWQyZ3uPyoNXesHrqdeQAXEiKJptindgAAAABJRU5ErkJggg=="
        case .cardbackborder4:
            return "iVBORw0KGgoAAAANSUhEUgAAAGQAAACMCAMAAAC9K/yJAAAAAXNSR0IArs4c6QAAAAlQTFRFAAAA////AAAAc8aDcQAAAAN0Uk5TAP//RFDWIQAAAOZJREFUaIHtm0EOgzAMBEn+/+gK0lRUhayFbFeyZi97QYzAnpxg23LSgzMYLTQHpbcBfJdu84WzMiH7U40ydBvdTV0SkjCT4LDCjwY/b9LdsoK4Hbr/gnzm5Ab5Gfz3SvtAVp64QS5WOAVSZ7vqQPDkHoInQPBEQ/AECJ5oCJ4AwRMNwRMgeKIheAIETzQET4BU265KMtbZrjoQPLmH4AkQPNEQPAGCJxqCJ0DwREPwBAieaAieAMETDcETN4hbFhBTP/28+jQn3eYLZ+VBgpP6ulIGXweSMpN4SPAOzx+1YuN16Iq8AEy1IiVaGw0AAAAAAElFTkSuQmCC"
        case .shinning:
            return "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAAXNSR0IArs4c6QAAAAlQTFRFAAAA////AAAAc8aDcQAAAAN0Uk5TAP//RFDWIQAAAClJREFUGJVjYAQCJiZGOGDAIgDiIoQwBWBMGD1QAghHQxyITwAihCEAAKcYATmw1+sbAAAAAElFTkSuQmCC"
        case .queen:
            return "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAAXNSR0IArs4c6QAAAAlQTFRFAAAA////AAAAc8aDcQAAAAN0Uk5TAP//RFDWIQAAAC9JREFUGJVjYAACJihggAImJjQRGIO+AnAHIAswoWmBCCGbge50JmSd2HzHgMQDAGQoAMliReDvAAAAAElFTkSuQmCC"
        case .cardbackcenter2:
            return "iVBORw0KGgoAAAANSUhEUgAAAGQAAACMCAMAAAC9K/yJAAAAAXNSR0IArs4c6QAAAAlQTFRFAAAA////AAAAc8aDcQAAAAN0Uk5TAP//RFDWIQAAAJxJREFUaIHt2tEJgDAQBUG1/6LtwLhwiOi8FLCZ/9s2MzN7zY595l1GhhrHSjKxleT6E7d2QzIQIUkRkhQhSRGSFCFJEZIUIUkRkhQhSRGSFCFJEZIUIUkRkhQhSRGSFCFJEZIUIUkRkhQhSRGSFCFJEZIUIUkRkhQhSRGSFCFJEZIUIUkRkhQhSRGSFPmTZOJqdCn5yJWtmZk9uhPajQbxGK5WzwAAAABJRU5ErkJggg=="
        case .six:
            return "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAAXNSR0IArs4c6QAAAAlQTFRFAAAA////AAAAc8aDcQAAAAN0Uk5TAP//RFDWIQAAACVJREFUGJVjYAACJihggAImJjQRGANDgIGBBAGybaGyAC6HgNgAXnQAs+y9GowAAAAASUVORK5CYII="
        case .cardbackcenter1:
            return "iVBORw0KGgoAAAANSUhEUgAAAGQAAACMCAMAAAC9K/yJAAAAAXNSR0IArs4c6QAAAAlQTFRFAAAA////AAAAc8aDcQAAAAN0Uk5TAP//RFDWIQAAAJ1JREFUaIHt2sEJgDAUBUG1/6ItQDAsfER0Xu5ZJudsm5mZvWbHPnNuI0ONYyGZ2FqSn/h6yVoyECFJEZIUIUkRkhQhSRGSFCFJEZIUIUkRkhQhSRGSFCFJEZIUIUkRkhQhSRGSFCFJEZIUIUkRkhQhSRGSFCFJEZIUIUkRkhQhSRGSFCFJEZIUIUkRkhT5k2Tk3+hC8pVftmZm9uhOTZoFlS8Z3XcAAAAASUVORK5CYII="
        case .two:
            return "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAAXNSR0IArs4c6QAAAAlQTFRFAAAA////AAAAc8aDcQAAAAN0Uk5TAP//RFDWIQAAACpJREFUGJVjYAACJghggAEmJlQRGAsugiTDgArQBZjQBAaaj/Abwi/IAgBPuACbr7VfXAAAAABJRU5ErkJggg=="
        case .ace:
            return "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAAXNSR0IArs4c6QAAAAlQTFRFAAAA////AAAAc8aDcQAAAAN0Uk5TAP//RFDWIQAAACVJREFUGJVjYAABJjBggAMmJlQRKBMhAmNQWQDNXiwCNLEWiQYAX6AAqbu74ycAAAAASUVORK5CYII="
        case .twobytwoalpha:
            return "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAAXNSR0IArs4c6QAAAAlQTFRFAAAA////AAAAc8aDcQAAAAN0Uk5TAP//RFDWIQAAABhJREFUGJVjYGJiYEDGDBgCWITQBIaRGQCJEAEByVysjAAAAABJRU5ErkJggg=="
        case .cardbackcenter5:
            return "iVBORw0KGgoAAAANSUhEUgAAAGQAAACMCAMAAAC9K/yJAAAAAXNSR0IArs4c6QAAAAlQTFRFAAAA////AAAAc8aDcQAAAAN0Uk5TAP//RFDWIQAAAKtJREFUaIHt2sENxCAQBEHj/IN2BkALdLpHzQbQLr95HjMz+5u9485NI5ca70pyYyvJO463IZl/xcbGjuQ8QpIiJClCkiIkKUKSIiQpQpIiJClCkiIkKUKSIiQpQpIiJClCkiIkKUKSIiQpQpIiJClCkiIkKUKSIiQpQpIiJClCkiIkKUKSIiQpQpIiJClCkiIkKbIhOX9suZbceDW6lty45f+8cdOImZn9dB+KkAhFQr0AGwAAAABJRU5ErkJggg=="
        case .heartshapefat:
            return "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAAXNSR0IArs4c6QAAAAlQTFRFAAAA////AAAAc8aDcQAAAAN0Uk5TAP//RFDWIQAAAEhJREFUGJWNjlEOACAIQoP7HzrzOV0/LTZHkIpr/UDSIUOp7dRy6wCchlVaGLyrzq7+Ndtn3pUTXA4p5FB9memaW2d+nFu/sAFokAC6Bu8o1wAAAABJRU5ErkJggg=="
        case .spadeshape:
            return "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAAXNSR0IArs4c6QAAAAlQTFRFAAAA////AAAAc8aDcQAAAAN0Uk5TAP//RFDWIQAAADVJREFUGJWVzzEOACAIBEEy/3+0URsPC+OGagoCVTsqIoUUUkihSQeavOFeOqXWnMf+/nI2AI7oAQGqn/seAAAAAElFTkSuQmCC"
        case .cardbackborder3:
            return "iVBORw0KGgoAAAANSUhEUgAAAGQAAACMCAMAAAC9K/yJAAAAAXNSR0IArs4c6QAAAAlQTFRFAAAA////AAAAc8aDcQAAAAN0Uk5TAP//RFDWIQAAAQpJREFUaIHt1MEOgjAURNHC/3+0iCBIW8wkM13ofSG85aGESyljZg7PCGNVlvu0zLxegb0hOeB57cj0Okxmv5Ekc0K2Ayb2GUkp45Hc/uFOXHO8sqqT2fjTPR770okPuenEiXQ7iSOzGel2YkT6nRi/rptObAidiAidKAidKAidOBA6aSN0IiF0IiJ0IiB0IiJ0oiB0oiB04kDopI3QiYTQiYjQiYDQiYjQiYLQiYLQiQOhkzZCJxJCJyJCJwJCJyJCJwpCJwpCJw6ETtoInUgInYgInQgInYgInSjIX3RinG4nkX39hBN7PJLb5bOTxK46Sey6k8CuOknskZ1Elf0k6SkDFNdP98s8AGn+HaEsfqZpAAAAAElFTkSuQmCC"
        case .cardbackborder2:
            return "iVBORw0KGgoAAAANSUhEUgAAAGQAAACMCAMAAAC9K/yJAAAAAXNSR0IArs4c6QAAAAlQTFRFAAAA////AAAAc8aDcQAAAAN0Uk5TAP//RFDWIQAAAONJREFUaIHt2tsKwjAQRdEk///R9UJbpZAzlskRhj0vESkucLJ9sjXPjMXjMF7K/rJHz/CD30h/zPO92Nnf54ieIHcQx+L70rFeYQtiWfzxISNtZkjaj+6fkHNPachl8R93Og2ZdZKGXK+wBalzu+ogdDJB6ASETjRCJyB0ohE6AaETjdAJCJ1ohE5A6EQjdAJS7XYVirHO7aqD0MkEoRMQOtEInYDQiUboBIRONEInIHSiEToBoRON0EkakjYTJHTe/Hv1ufjIGX5w/2Qf0peO9euyLB7kJ8Sy+MXTDErWj66YDebVIwlcVDZyAAAAAElFTkSuQmCC"
        case .zero:
            return "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAAXNSR0IArs4c6QAAAAlQTFRFAAAA////AAAAc8aDcQAAAAN0Uk5TAP//RFDWIQAAADxJREFUGJVlz0EOACAIA8Gm/3+0QUVh6QknJBYp4h292F3u+CUHAjcMMCBeFXyw1hAA31qAUQzVx3Ht/AVpMADFQ1tHWQAAAABJRU5ErkJggg=="
        case .cardbackcenter4:
            return "iVBORw0KGgoAAAANSUhEUgAAAGQAAACMCAMAAAC9K/yJAAAAAXNSR0IArs4c6QAAAAlQTFRFAAAA////AAAAc8aDcQAAAAN0Uk5TAP//RFDWIQAAAR9JREFUaIHtl8EOgzAMQ8H//9ETO4wIRuOoUCXFRlUvVV3zMIJlkSRJktJodYTmwG/uMmHlmMA9M8x8dWVIchbLIWOS5hJH9NPVZ7LdvcdNRiVhetJnMiIJKCbOOTwTMQmZcEwqJHkbkxo9wWuYYComFZJ8v4maS+ZhAvVkN0nEpEISpic1kryLSZ2ezPF0zdMTJQmZzJMETBLvHeqaiEnEZNvh8V9sMYmZMEyK9ARiEjBJ0hOIyW6SpCdiYkzEJGSyqb1ETOwOOXoCMTE75OhJESZgmJRJMgeTlUmintgdlIQ3UZKQCZPEe4e6JoOSOCZiYk3EJGRCMukSmSR0wcz78JIc1x8HzHypm5P8z0YwiZ57SJLzPW2aSJIkSUP1ARaeCwELWJYcAAAAAElFTkSuQmCC"
        case .three:
            return "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAAXNSR0IArs4c6QAAAAlQTFRFAAAA////AAAAc8aDcQAAAAN0Uk5TAP//RFDWIQAAAC1JREFUGJVjYAACJihggAImJjQRKANJCaoECQIoZqBai02AYmsxnI7hORTvAwBRJACZd09/nAAAAABJRU5ErkJggg=="
        case .four:
            return "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAAXNSR0IArs4c6QAAAAlQTFRFAAAA////AAAAc8aDcQAAAAN0Uk5TAP//RFDWIQAAACZJREFUGJVjYAADJiYIhgN0ATAbnwCEiUcAysIrAAU4BVB10kIAAElOAH0eKsOdAAAAAElFTkSuQmCC"
        case .cardbackcenter6:
            return "iVBORw0KGgoAAAANSUhEUgAAAGQAAACMCAMAAAC9K/yJAAAAAXNSR0IArs4c6QAAAAlQTFRFAAAA////AAAAc8aDcQAAAAN0Uk5TAP//RFDWIQAAAK9JREFUaIHt2iEOxDAQBMEk/3/0sYO2W15YszCgVQr185iZ2cHesa0i39AtI2OVjWRiO8l3/z8OJKvvR3tPJPcRkhQhSRGSFCFJEZIUIUkRkhQhSRGSFCFJEZIUIUkRkhQhSRGSFCFJEZIUIUkRkhQhSRGSFCFJEZIUIUkRkhQhSRGSFCFJEZIUIUkRkhQhSRGSFCFJkQPJ/WPLvWTi1eheMnEbydAtI1NbRMzM7L8froAJuVNFnYAAAAAASUVORK5CYII="
        case .orbs:
            return "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAAXNSR0IArs4c6QAAAAlQTFRFAAAA////AAAAc8aDcQAAAAN0Uk5TAP//RFDWIQAAAClJREFUGJVjYGRkAgMYzYAhAGKCAITGL4ChhWgBYt0BEQIBbAIwQLYAANpwAZnJb479AAAAAElFTkSuQmCC"
        case .squigglebrick:
            return "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAAXNSR0IArs4c6QAAAAlQTFRFAAAA////AAAAc8aDcQAAAAN0Uk5TAP//RFDWIQAAADFJREFUGJVjYEQCTEDAgCHAxITggkhMARgDJoFNAGIYTCN2AWRB3AIwg/ELgITIEAAAqFABNYMSqU8AAAAASUVORK5CYII="
        case .cardbackborder1:
            return "iVBORw0KGgoAAAANSUhEUgAAAGQAAACMCAMAAAC9K/yJAAAAAXNSR0IArs4c6QAAAAlQTFRFAAAA////AAAAc8aDcQAAAAN0Uk5TAP//RFDWIQAAAR9JREFUaIHt2s0KwjAQAOEm7//Q1v7XksjAbjw4CzVtD36EMJ6cpjFTk2eEsSjzZ0mcHZnv1qeas67Icl+2d8HrgZRtLynXuZOcXbzXcyd553FB1qeUdfiZ5O3mQPZ3kdPqpNSw6XRSw350L9/50Ukk0ukkEGl2ErqTVifJZ7KpkUirk0ik3UkcYicMsROG2AlA7IQhdoIQOyGInSDEThBiJwyxE4bYCUDshCF2ghA7IYidIMROEGInDLEThtgJQOyEIXaCEDshiJ0gxE4QYicMsROG2AlA7IQhdoIQOyGInSDEThBiJwyxE4b8QSdh0+kkcDqdxK/PThLW55lkXD/5X33Seu8kYx17JiVpF9czie7wNnVHkmcaoET96H6ZF7cjIHrfAF52AAAAAElFTkSuQmCC"
        case .cardinnerscales:
            return "iVBORw0KGgoAAAANSUhEUgAAAGQAAACMCAMAAAC9K/yJAAAAAXNSR0IArs4c6QAAAAlQTFRFAAAA////AAAAc8aDcQAAAAN0Uk5TAP//RFDWIQAAAJxJREFUaIHt0zEOgCAMQFHK/Q+tQRRHhxaXZ0x+cLARea3tuSKij7ukz4xzNZ5V9BpS9vqr80vmqqj3dpVO2Tmk7qevIYXHt8f7CHPyoZxwwgknnHCSUU444YQTTjjJKCeccMIJJ5xklBNOOOGEE04yygknnHDCCScZ5YQTTjjhhJOMcsIJJ5xwwklGOeGEE044+d9Jq9uq5WTDdQAFKj2e14WzpAAAAABJRU5ErkJggg=="
        case .depthbox:
            return "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAAXNSR0IArs4c6QAAAAlQTFRFAAAA////AAAAc8aDcQAAAAN0Uk5TAP//RFDWIQAAACBJREFUGJVjYGJiZGRCAgwYAoxoAFOAsBnEC2AYSl8BANdYAYW9dbiQAAAAAElFTkSuQmCC"
        case .windowtop:
            return "iVBORw0KGgoAAAANSUhEUgAAABYAAAAiCAMAAABsgdmyAAAAAXNSR0IArs4c6QAAAAlQTFRFAAAA////AAAAc8aDcQAAAAN0Uk5TAP//RFDWIQAAABtJREFUKJFjYMQKGAZAmAkrwCU8avZINZuGwgANFAP1QTu0UQAAAABJRU5ErkJggg=="
        case .king:
            return "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAAXNSR0IArs4c6QAAAAlQTFRFAAAA////AAAAc8aDcQAAAAN0Uk5TAP//RFDWIQAAADpJREFUGJVjYGBgYmKAABgDQaMKMKGpRPAhAkh8sAAyHySAwgfxUPjYBDC0YBqKaS2mwzCdjuk5KAMAVOYAnVJXj0IAAAAASUVORK5CYII="
        case .diamond:
            return "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAAXNSR0IArs4c6QAAAAlQTFRFAAAA////AAAAc8aDcQAAAAN0Uk5TAP//RFDWIQAAACtJREFUGJVjYEQDDDgFmJjwC4C4ECHsAjAuCGMTQOYyMWETIGwGMe7A6xcAppABQdE9i5IAAAAASUVORK5CYII="
        case .vertical:
            return "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAAXNSR0IArs4c6QAAAAlQTFRFAAAA////AAAAc8aDcQAAAAN0Uk5TAP//RFDWIQAAABJJREFUGJVjYGJiZETGDCNbAADNkAGBjmio+wAAAABJRU5ErkJggg=="
        case .theme:
            return "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAAXNSR0IArs4c6QAAAAlQTFRFAAAA////AAAAc8aDcQAAAAN0Uk5TAP//RFDWIQAAADdJREFUGJVjYAABJjBggAEmOIDzGcEAKgLiQ+ShIiAGRBokAuczwtTQRgDDWkyHYTgd03Oo3gcAvOcBYy2GRjoAAAAASUVORK5CYII="
        case .clubshape:
            return "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAAXNSR0IArs4c6QAAAAlQTFRFAAAA////AAAAc8aDcQAAAAN0Uk5TAP//RFDWIQAAADBJREFUGJVjYIAAJiYGFMDEhCrCxIQmQlgAzQwQB4yYkNUj6SIsgGEGWU5HNRINAABqyADJgxWReQAAAABJRU5ErkJggg=="
        case .box_checked:
            return "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAAXNSR0IArs4c6QAAAAlQTFRFAAAA////AAAAc8aDcQAAAAN0Uk5TAP//RFDWIQAAAEFJREFUGJV1z1EKACAIREHX+x86NSx50X6EDZhmjpi7RhI0JC4BV7JOaKmyQOPYoNPYoB72BbbwUY7lYlz9+RyyALfQAVlxEzB8AAAAAElFTkSuQmCC"
        case .bottomarrowdark:
            return "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAAXNSR0IArs4c6QAAAAlQTFRFAAAA////AAAAc8aDcQAAAAN0Uk5TAP//RFDWIQAAADFJREFUGJVjYEIDDEyMKACHAFQ1+QIoAKwCmQ/RgsTHZSgjnA93KYyPcDrMB9j8ggYA0ygBit2sKDgAAAAASUVORK5CYII="
        case .ten:
            return "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAAXNSR0IArs4c6QAAAAlQTFRFAAAA////AAAAc8aDcQAAAAN0Uk5TAP//RFDWIQAAAClJREFUGJVjYGBgYmIAEWDAAGHC+TA5KMEAVwLVBqMGuQCG01G8i+x9AH++AO1FwJGPAAAAAElFTkSuQmCC"
        case .cardinnerbordertest:
            return "iVBORw0KGgoAAAANSUhEUgAAAGQAAACMCAMAAAC9K/yJAAAAAXNSR0IArs4c6QAAAAlQTFRFAAAA////AAAAc8aDcQAAAAN0Uk5TAP//RFDWIQAAAJdJREFUaIHt0zkOwCAMBEDw/x+dg5DexabJWLIsqhXgGUO1as6aq1LzCqlap9g8Q+rJzPX9XMlbXHOHRP/lvUkwY4dk92uFhHeYk1ZzwgknnHDCCSeccMIJJ8EsTlrNCSeccMIJJ5xwwgknnASzOGk1J5xwwgknnHDCCSeccBLM4qTVnHDCCSeccMIJJ5xw8mMn8R0e39QB+gY+jdoseykAAAAASUVORK5CYII="
        }
    }
}
